# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShapeDetector' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShapeDetector
  pod 'Fritz', '~> 1.0.0-beta'
end
